// <auto-generated />
using System;
using EnduranceTracker.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnduranceTracker.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260329100830_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EnduranceTracker.Core.Entities.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AvgHeartRate")
                        .HasColumnType("int");

                    b.Property<double?>("AvgPace")
                        .HasColumnType("float");

                    b.Property<double?>("AvgSpeed")
                        .HasColumnType("float");

                    b.Property<int?>("Calories")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Distance")
                        .HasColumnType("float");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("time");

                    b.Property<double?>("ElevationGain")
                        .HasColumnType("float");

                    b.Property<int?>("MaxHeartRate")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RawJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<long?>("StravaActivityId")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StravaActivityId")
                        .IsUnique()
                        .HasFilter("[StravaActivityId] IS NOT NULL");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Date");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("EnduranceTracker.Core.Entities.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Discipline")
                        .HasColumnType("int");

                    b.Property<double?>("Distance")
                        .HasColumnType("float");

                    b.Property<double?>("ElevationGain")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("TargetTime")
                        .HasColumnType("time");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Date");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("EnduranceTracker.Core.Entities.PlannedSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CompletedActivityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("TargetDistance")
                        .HasColumnType("float");

                    b.Property<TimeSpan?>("TargetDuration")
                        .HasColumnType("time");

                    b.Property<string>("TargetIntensity")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompletedActivityId");

                    b.HasIndex("PlanId");

                    b.ToTable("PlannedSessions");
                });

            modelBuilder.Entity("EnduranceTracker.Core.Entities.SavedView", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FilterJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SavedViews");
                });

            modelBuilder.Entity("EnduranceTracker.Core.Entities.StrengthDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Exercise")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Reps")
                        .HasColumnType("int");

                    b.Property<int?>("Sets")
                        .HasColumnType("int");

                    b.Property<double?>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.ToTable("StrengthDetails");
                });

            modelBuilder.Entity("EnduranceTracker.Core.Entities.TrainingPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("GeneratedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlanJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("TrainingPlans");
                });

            modelBuilder.Entity("EnduranceTracker.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EncryptedStravaAccessToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EncryptedStravaRefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntraObjectId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<long?>("StravaAthleteId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("StravaTokenExpiry")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EntraObjectId")
                        .IsUnique();

                    b.HasIndex("StravaAthleteId")
                        .IsUnique()
                        .HasFilter("[StravaAthleteId] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EnduranceTracker.Core.Entities.Activity", b =>
                {
                    b.HasOne("EnduranceTracker.Core.Entities.User", "User")
                        .WithMany("Activities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EnduranceTracker.Core.Entities.Event", b =>
                {
                    b.HasOne("EnduranceTracker.Core.Entities.User", "User")
                        .WithMany("Events")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EnduranceTracker.Core.Entities.PlannedSession", b =>
                {
                    b.HasOne("EnduranceTracker.Core.Entities.Activity", "CompletedActivity")
                        .WithMany()
                        .HasForeignKey("CompletedActivityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EnduranceTracker.Core.Entities.TrainingPlan", "Plan")
                        .WithMany("Sessions")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompletedActivity");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("EnduranceTracker.Core.Entities.SavedView", b =>
                {
                    b.HasOne("EnduranceTracker.Core.Entities.User", "User")
                        .WithMany("SavedViews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EnduranceTracker.Core.Entities.StrengthDetail", b =>
                {
                    b.HasOne("EnduranceTracker.Core.Entities.Activity", "Activity")
                        .WithMany("StrengthDetails")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");
                });

            modelBuilder.Entity("EnduranceTracker.Core.Entities.TrainingPlan", b =>
                {
                    b.HasOne("EnduranceTracker.Core.Entities.Event", "Event")
                        .WithOne("TrainingPlan")
                        .HasForeignKey("EnduranceTracker.Core.Entities.TrainingPlan", "EventId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EnduranceTracker.Core.Entities.User", "User")
                        .WithMany("TrainingPlans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EnduranceTracker.Core.Entities.Activity", b =>
                {
                    b.Navigation("StrengthDetails");
                });

            modelBuilder.Entity("EnduranceTracker.Core.Entities.Event", b =>
                {
                    b.Navigation("TrainingPlan");
                });

            modelBuilder.Entity("EnduranceTracker.Core.Entities.TrainingPlan", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("EnduranceTracker.Core.Entities.User", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Events");

                    b.Navigation("SavedViews");

                    b.Navigation("TrainingPlans");
                });
#pragma warning restore 612, 618
        }
    }
}
